DROP TABLE IF EXISTS Enrollments;
DROP TABLE IF EXISTS Lessons;
DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Auditoriums;
DROP TABLE IF EXISTS Wizards;
DROP TABLE IF EXISTS Houses;
DROP TABLE IF EXISTS Roles;