DROP TABLE IF EXISTS Houses CASCADE;
DROP TABLE IF EXISTS Roles CASCADE; 
DROP TABLE IF EXISTS Wizards CASCADE;
DROP TABLE IF EXISTS Subjects CASCADE; 
DROP TABLE IF EXISTS Auditoriums CASCADE;
DROP TABLE IF EXISTS Enrollments CASCADE;
DROP TABLE IF EXISTS Lessons CASCADE;
DROP TABLE IF EXISTS Years CASCADE;
